name: Build & deploy docs

on: [push]

jobs:
  build-docs:
    name: Build and deploy documentation
    runs-on: ubuntu-latest
    if: github.repository == 'StanfordVL/bddl' && github.ref == 'refs/heads/master'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
        architecture: x64

    - name: Install dev requirements
      run: pip install -r requirements-dev.txt

    - name: Generate docs
      working-directory: ./docs
      run: make html

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html
